# Generated by Django 6.0.6 on 2026-06-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_bengali_sweets_product_is_dry_sweets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_bengali_sweets',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_dry_sweets',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_festival_special',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_gift_box',
        ),
    ]
